- name: all datatypes play 1
  hosts: localhost
  vars:
    Name: Jashwanth Yarrarapu
    Skills:
    - DevOps
    - AWS
    - Kubernetes
    - Docker
    - Terraform
    - Prometheus
    - Grafana
    - Kibana
    - CloudWatch
    - Shell
    - CFT
  tasks:
  - name: datatypes in play 1
    ansible.builtin.debug:
      msg: "My Name is: {{Name}}"
  - name: datatypes in play 1
    ansible.builtin.debug:
      msg: "My skills are: {{Skills}}"

- name: all datatypes play 2
  hosts: localhost
  vars:
    Experience:
      Overall: "5 years"
      Barclays: "2 years"
      Kohls: "2 years"
      Wipro: "2 years"
    DevOps: true
  tasks:
  - name: datatypes in play 2
    ansible.builtin.debug:
      msg: "My experience: {{Experience}}"
  - name: datatypes in play 2
    ansible.builtin.debug:
      msg: "is he a DevOps Engineer: {{DevOps}}"