- name: install package from loops
  hosts: localhost
  become: yes
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - mysql
    - postfix