- name: Variables in ansible
  hosts: localhost
  vars:
    Fname: "Jashwanth"
    Lname: "Yarrarapu"
    Course: "DevOps"
  tasks:
  - name: Display variables in ansible
    ansible.builtin.debug:
      msg: "Hello There, my name is {{Fname} {{Lname}} and I am learning {{Course}}"